name: Setup Jelly CLI
description: Download Jelly CLI and add it to PATH

inputs:
  version: 
    description: Version of Jelly CLI to install
    default: "latest"
  token:
    description: GitHub token for finding the latest release
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Setup Jelly CLI (Unix-like)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_VERSION: ${{ inputs.version }}
      run: $GITHUB_ACTION_PATH/unix-like.sh
        
    - name: Setup Jelly CLI (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_VERSION: ${{ inputs.version }}
      run: '& $env:GITHUB_ACTION_PATH\windows.ps1'
