name: Setup Jelly CLI
description: Download Jelly CLI and add it to PATH

inputs:
  version: 
    description: Version of Jelly CLI to install
    default: "latest"
  token:
    description: GitHub token for finding the latest release
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Setup Jelly CLI (Linux x86_64)
      if: runner.os == 'Linux'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_VERSION: ${{ inputs.version }}
      run: $GITHUB_ACTION_PATH/unix-like.sh
        
    
    - name: Setup Jelly CLI (Other)
      if: runner.os != 'Linux'
      shell: bash
      run: |
        echo "::error::Support for platforms other than Linux x86_64 is not yet implemented"
        exit 1
